development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://haqcqzdausbivj:8OBnbNJndlAv7JO8V7PW_wAZuy@ec2-54-235-255-27.compute-1.amazonaws.com:5432/d6alvrtv7as0en